name: NoMoreESP
main: tw.mics.spigot.plugin.nomoreesp.NoMoreESP
version: ${project.version}
description: ${project.description}
author: Mics
website: https://mics.tw
api-version: 1.13

depend: [ProtocolLib]